### ISSUE TITLE
能加个启动说明吗

### ISSUE THREAD

**Issue by ghost** [rsuite/rsuite-v1-example#1]
完全不知道怎么本地启动

**Comment by simonguo** [comment]
@javrven  
你代码在本地，
1.先执行，`npm install` 安装依赖
2.然后 执行 `npm run dev` , 启动 webpack server
3.然后访问 http://127.0.0.1:3000

另外在 ，https://github.com/rsuite/rsuite-example-admin/blob/master/package.json#L5 
package.json 中有 scripts 说明。
